import enum

class SupportedDevice(enum.Enum):
	Q200 = 0
	Q100 = 1
	Q100V1 = 2
	P855 = 3
	P850 = 4
	IOUnit = 5
	SICAM_T = 6
	MMU = 7

class INFODataSource(enum.Enum):
	HTML = 0
	MODBUSTCP = 1
	MODBUSRTU = 2
	IEC61850 = 3
	FTPS = 4

class DecimalSeparator(enum.Enum):
	COMMA = 0
	POINT = 1

class DeviceStatus(enum.Enum):
	DEVICE_OK = 1
	BATTERY_FAILURE = 2
	SD_CARD_STATUS = 3
	SETTING_LOAD = 4
	SETTING_CHECK = 5
	SETTING_ACTIVATE = 6
	DIRECTION_OF_ROTATION = 7

class DeviceCommIndication(enum.Enum):
	INDICATION_1_FROM_REMOTE = 1
	INDICATION_2_FROM_REMOTE = 2
	INDICATION_3_FROM_REMOTE = 3
	INDICATION_4_FROM_REMOTE = 4
	INDICATION_5_FROM_REMOTE = 5
	INDICATION_6_FROM_REMOTE = 6
	INDICATION_7_FROM_REMOTE = 7
	INDICATION_8_FROM_REMOTE = 8
	INDICATION_9_FROM_REMOTE = 9
	INDICATION_10_FROM_REMOTE = 10
	INDICATION_11_FROM_REMOTE = 11
	INDICATION_12_FROM_REMOTE = 12
	INDICATION_13_FROM_REMOTE = 13
	INDICATION_14_FROM_REMOTE = 14
	RESET_ENERGY = 15
	PARAMETER_LOAD = 16
	TIME_SYN_ERROR = 17
	SIGNAL_ROTATION = 18
	SD_CARD_ERROR = 19
	SENSITIVE_CURVE_VIOLATION_ALARM = 20

class DeviceIndicationState(enum.Enum):
	OFF = 0
	ON = 1
	INVALID = 2
	UNCONFIGURED = 3
